"""add_fila_espera

Revision ID: 18e03ff4a210
Revises: 3aed098b8ee6
Create Date: 2026-04-04 11:40:54.857362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18e03ff4a210'
down_revision: Union[str, None] = '3aed098b8ee6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fila_espera',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=True),
    sa.Column('convenio_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('AGUARDANDO', 'NOTIFICADO', 'AGENDADO', 'CANCELADO', name='fila_espera_status'), nullable=False),
    sa.Column('notificado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['convenio_id'], ['convenios.id'], ),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fila_espera_estabelecimento_id'), 'fila_espera', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_fila_espera_paciente_id'), 'fila_espera', ['paciente_id'], unique=False)


def downgrade() -> None:
    op.drop_index(op.f('ix_fila_espera_paciente_id'), table_name='fila_espera')
    op.drop_index(op.f('ix_fila_espera_estabelecimento_id'), table_name='fila_espera')
    op.drop_table('fila_espera')
    sa.Enum(name='fila_espera_status').drop(op.get_bind(), checkfirst=True)
