"""add_contato_responsavel_estabelecimento

Revision ID: 7d076b3ea7af
Revises: ecb3f8465cc0
Create Date: 2026-04-04 01:41:00.885079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d076b3ea7af'
down_revision: Union[str, None] = 'ecb3f8465cc0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('estabelecimentos', sa.Column('email', sa.String(length=254), nullable=True))
    op.add_column('estabelecimentos', sa.Column('telefone', sa.String(length=20), nullable=True))
    op.add_column('estabelecimentos', sa.Column('endereco', sa.String(length=500), nullable=True))
    op.add_column('estabelecimentos', sa.Column('cidade', sa.String(length=100), nullable=True))
    op.add_column('estabelecimentos', sa.Column('estado', sa.String(length=2), nullable=True))
    op.add_column('estabelecimentos', sa.Column('cep', sa.String(length=8), nullable=True))
    op.add_column('estabelecimentos', sa.Column('responsavel_nome', sa.String(length=200), nullable=True))
    op.add_column('estabelecimentos', sa.Column('responsavel_cpf', sa.String(length=11), nullable=True))
    op.add_column('estabelecimentos', sa.Column('responsavel_email', sa.String(length=254), nullable=True))
    op.add_column('estabelecimentos', sa.Column('responsavel_telefone', sa.String(length=20), nullable=True))
    op.add_column('estabelecimentos', sa.Column('responsavel_cargo', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('estabelecimentos', 'responsavel_cargo')
    op.drop_column('estabelecimentos', 'responsavel_telefone')
    op.drop_column('estabelecimentos', 'responsavel_email')
    op.drop_column('estabelecimentos', 'responsavel_cpf')
    op.drop_column('estabelecimentos', 'responsavel_nome')
    op.drop_column('estabelecimentos', 'cep')
    op.drop_column('estabelecimentos', 'estado')
    op.drop_column('estabelecimentos', 'cidade')
    op.drop_column('estabelecimentos', 'endereco')
    op.drop_column('estabelecimentos', 'telefone')
    op.drop_column('estabelecimentos', 'email')
    # ### end Alembic commands ###
