"""initial_schema

Revision ID: 89102304387e
Revises: 
Create Date: 2026-04-03 22:23:18.774226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '89102304387e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especialidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('cor_hex', sa.String(length=7), nullable=True),
    sa.Column('icone', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('convenio', sa.String(length=100), nullable=True),
    sa.Column('numero_carteirinha', sa.String(length=50), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crm', sa.String(length=20), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('duracao_consulta_min', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crm')
    )
    op.create_table('sessoes_chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_token', sa.String(length=100), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=True),
    sa.Column('canal', sa.Enum('PORTAL', 'WHATSAPP', name='sessao_canal'), nullable=False),
    sa.Column('status', sa.Enum('ATIVA', 'ENCERRADA', 'AGENDOU', 'ABANDONOU', name='sessao_status'), nullable=False),
    sa.Column('modelo_ia_usado', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('encerrada_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_table('slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('status', sa.Enum('DISPONIVEL', 'BLOQUEADO', 'AGENDADO', 'ENCAIXE', name='slot_status'), nullable=False),
    sa.Column('motivo_bloqueio', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('modelo', sa.String(length=100), nullable=False),
    sa.Column('feature', sa.Enum('TRIAGEM', 'AGENDAMENTO', 'RAG', 'RESUMO', 'GERAL', name='token_feature'), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=6), nullable=False),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessoes_chat.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('senha_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.Enum('RECEPCIONISTA', 'MEDICO', 'ADMIN', name='usuario_role'), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('consultas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('paciente_id', sa.Integer(), nullable=False),
    sa.Column('medico_id', sa.Integer(), nullable=False),
    sa.Column('especialidade_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('EXTERNO', 'INTERNO', 'ENCAIXE', 'RETORNO', name='consulta_tipo'), nullable=False),
    sa.Column('status', sa.Enum('AGENDADA', 'CONFIRMADA', 'CANCELADA', 'REALIZADA', 'FALTA', name='consulta_status'), nullable=False),
    sa.Column('triagem_resumo', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('urgencia', sa.Enum('BAIXA', 'MEDIA', 'ALTA', 'EMERGENCIA', name='consulta_urgencia'), nullable=False),
    sa.Column('canal_origem', sa.Enum('PORTAL', 'WHATSAPP', 'INTERNO', name='consulta_canal'), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['especialidade_id'], ['especialidades.id'], ),
    sa.ForeignKeyConstraint(['medico_id'], ['medicos.id'], ),
    sa.ForeignKeyConstraint(['paciente_id'], ['pacientes.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('consultas')
    op.drop_table('usuarios')
    op.drop_table('token_usage')
    op.drop_table('slots')
    op.drop_table('sessoes_chat')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.drop_table('pacientes')
    op.drop_table('especialidades')
    # ### end Alembic commands ###
