"""add_auditoria_acoes

Revision ID: b7d6df81f0c1
Revises: aef53d41f21e
Create Date: 2026-04-08 21:13:57.349143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b7d6df81f0c1'
down_revision: Union[str, None] = 'aef53d41f21e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditoria_acoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('usuario_role', sa.String(length=50), nullable=False),
    sa.Column('acao', sa.Enum('ACESSO_CLINICA', 'LICENCA_ALTERADA', 'ESTAB_ALTERADO', 'USUARIO_ALTERADO', 'LOGIN', 'LOGOUT', name='tipo_auditoria', create_constraint=True), nullable=False),
    sa.Column('estabelecimento_id', sa.Integer(), nullable=True),
    sa.Column('entidade', sa.String(length=50), nullable=True),
    sa.Column('entidade_id', sa.Integer(), nullable=True),
    sa.Column('detalhes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_origem', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['estabelecimento_id'], ['estabelecimentos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditoria_acoes_acao'), 'auditoria_acoes', ['acao'], unique=False)
    op.create_index(op.f('ix_auditoria_acoes_created_at'), 'auditoria_acoes', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditoria_acoes_estabelecimento_id'), 'auditoria_acoes', ['estabelecimento_id'], unique=False)
    op.create_index(op.f('ix_auditoria_acoes_usuario_id'), 'auditoria_acoes', ['usuario_id'], unique=False)
    op.drop_constraint(op.f('estabelecimentos_slug_key'), 'estabelecimentos', type_='unique')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=False)
    op.drop_constraint(op.f('fk_token_usage_estabelecimento'), 'token_usage', type_='foreignkey')
    op.create_foreign_key(None, 'token_usage', 'estabelecimentos', ['estabelecimento_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'token_usage', type_='foreignkey')
    op.create_foreign_key(op.f('fk_token_usage_estabelecimento'), 'token_usage', 'estabelecimentos', ['estabelecimento_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_pacientes_cpf'), table_name='pacientes')
    op.create_index(op.f('ix_pacientes_cpf'), 'pacientes', ['cpf'], unique=True)
    op.create_unique_constraint(op.f('estabelecimentos_slug_key'), 'estabelecimentos', ['slug'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_auditoria_acoes_usuario_id'), table_name='auditoria_acoes')
    op.drop_index(op.f('ix_auditoria_acoes_estabelecimento_id'), table_name='auditoria_acoes')
    op.drop_index(op.f('ix_auditoria_acoes_created_at'), table_name='auditoria_acoes')
    op.drop_index(op.f('ix_auditoria_acoes_acao'), table_name='auditoria_acoes')
    op.drop_table('auditoria_acoes')
    # ### end Alembic commands ###
